travis:
  secure:
    BINSTAR_TOKEN: RaEwug9LigebNLYN4Lfs7QTUgesgi7o+yMtB7XgremaP8EXpN1O/cnOXmc0Mo5B1K0E8bZerhc+4maVE+FHmUDbajeW17hbL3snwufMnG5RvUWELheSnoF5DRNRqG4Qmwz4irOb74CxKPnWvi3s9hXvpW8Hl7ZHPV2n8bnZUvJxFKJMqHA/r5rjjtlF/ZDT4cpwvNP+fsxDbbNPuHC4Oj9yK08WyOObxkQn4nCa2+SyhQ7qClMoER/RV9UcabWTXlaSh1dqPvJCV2phS9V/QlFeA55ZKuIaKUuJkV7A2K16zso7fLkzjazQyN0V7/0YTVMQi5AlNdI3hr6b6Tes6tMDyqJSIMVUoXoXTTxZsXC+yqC/BpNIiDsZZbSfBEZXLp1kSSJ0lvV5r/s0Sm4cWUOY6jAswsc7YnBXPDYwAOUI5XsttFQQx0q/CSg6ghKQI0GrNXNSYtixiTlj2/hwzzsq/iQ7FMtR6RwI9jKsM2Pan/qkEpXs/dtbV7YgQ1S0gaO14KCoFk7j3vyzqTWsMiaXWWNeUN4lxkj3qK3nrqfNTjnN2Xkouf6Hvm7oXuIKniphOAbYVHiPAY8/pbt9BWE4FuZQA2oE8lImzh1zRB+Q6jd/zLrOa/4HQzE5LfCA3MsFqGuLU3cvgKq4ic86nMxn9NeIjP5ohmjexnj1ZftU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
