travis:
  secure:
    BINSTAR_TOKEN: RYyMhRXyupjb9+IhBsB4jv0EznC3k3kKyWd29NM6Cdh6fr/vZA6ZuCkOxaawic+wEYlZkJdi0pidSFy+ofh39qVtwj8zc1xz//Q0orrwLjzNLMX3ex8a4U7Isx/p281lL8RI9692tM/cprqPnn+Ih6CdeAkNmMjAM/3GioKrIPbGBYcq9g45XBJdVv18GBxPwSPcq+FsQOitIIxqi+uGcMaNewv+FGE/0UrHTALBnucCZ2iM1yWp2sw8shaZeMByqvstUQFaVFB7qRoO7u2uCn7uhrIC+CFyHOwB6sPjwqX6W9rXRYId8eYlh47NLH6PxG9JQGs9UtFS4o1w4lB0iU4F9TWneyucDCN3iuRaLVDk4KblAfzcyhb7D5bFfAAjUYxNrey3DWScaz+zreNiaEYeh5xCSCPBZHQS+eKWeVsTEuY5kHuLo5xaWloe3A4n8Tt0lWbza5VVGBF42S4waQw+bFQhp/Le/eG3AQCqjdMg7K/JXRz1tIWJo8pwFoTL6Z9GTg2l3K7X0v5PVAEmYHTVB2nvXWoNCnTKS7HlgIqoUynS8QCJKt8LiW1J/42tmaAdF2RefHSKN4ApnrKKc13j+b2qB2nXhgUf5BFlLqQarkRPjYQsskKx8gs1jqLX0Kz4695RLkK83sOJwY9XfbfjenTedCSdQf6zijCvuWc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
