travis:
  secure:
    BINSTAR_TOKEN: hCyZioL+vR1g5YRrn+pOIHx+6YBTjSKwxnCy5sfae37ManTwjyj9CMMgxbKySmKSDOgPnfSod8mn4s+DxmmCFTHBUezFtngg4kggQND630gnQRNAyQV+z28PHbuMS3lpkRejOEOQYkH73OGJiNeBfZ8edGGMhnYO66Bm7zexYXy7JxXgdTs/kW7aBzbLjKzgoU7ZoTcZlWAv3M/2DLEhPIXobv5CpayeKNEMV66W4HOmFG6C/aOVldfL5ZmhnDurdux6hyZgg98uFRrgVmrozv98XLasS1Pw2U2PLTRtLk8QYtPtjBo3vD+GO9Pg2JdCqEucgv5v+OW6lmOh2Je31J4zQLZR/FuGjFA34Ph+0i0xEgvqhUk8M++9gcw8JQIPwuQcDcwIQQ4rNCka66lPg0XCsj06YY9Qd/AMo4QysodS5E6H9vzB2E7eK7eRJw8mhiNgQDGfW+Nf7kv3LO4sxyvN0p1QdsrjWsuCFqqXHxHy1CoSv9xLbqOoyKZqdbilbi2EOLfYcdekIqungya9S+/Aat3apwAjRbECqK8ohzFp7Efl3Y+N5vI1j6PmoyrhThVrAz4PxmHeOcuzQcN+0dn7+1B+FjmdS8aUTjKvX6MASp/e4LYjMophHRtUD6k+B/i9vZ8NHjEYS7sFuxeX6JNFbidq0jziyxWH/MYiX3w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
